cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "check t00-simple [x86_64-linux]",
  "check t01-signing [x86_64-linux]",
  "check t02-varnish [x86_64-linux]",
  "devShell default [x86_64-linux]",
  "package default [x86_64-linux]",
  "package harmonia [x86_64-linux]"
]
