name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fmt:
    name: Check rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build and Test Job
    timeout-minutes: 360
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nixpkgs: [ nixos-22.05, nixos-unstable ]

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs }}
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

    - name: nix-build (for ${{ matrix.nixpkgs }})
      run: nix-build -E 'with import <nixpkgs> {}; callPackage ./test.nix {nixpkgs = pkgs;}'
